neu

diff --git a/trunk/bin/Nhi1BuildLanguage b/trunk/bin/Nhi1BuildLanguage
--- a/trunk/bin/Nhi1BuildLanguage
+++ b/trunk/bin/Nhi1BuildLanguage
@@ -11,7 +11,7 @@
 #:              please contact AUTHORS for additional information
 #:
 
-set -ue
+set -u
 
 ## =======================================================================
 ##
@@ -21,26 +21,18 @@ set -ue
 ##
 ## =======================================================================
 
-## delete all environment variables to setup a "clean" build environment
-[[ "${CLEAN:-}" != "yes" ]] && exec /usr/bin/env - \
-  CLEAN="yes" TERM="$TERM" HOME="$HOME" MACHTYPE="$MACHTYPE" \
-    CC="${CC:-}" CXX="${CXX:-}" CCACHE_DIR="${CCACHE_DIR:-}" \
-      NHI1_TOOL_ROOT="${NHI1_TOOL_ROOT:-$HOME/ext/$MACHTYPE}" "$0" "$@"
-
-declare -x PATH="/bin:/usr/bin"
-
-Die() {
+die() {
   echo "ERROR: $*"
   exit 1
 }
 
 pathExtension() {
   case "$1" in
-    thread)		    echo "test";;
-    nothread)		    echo "test/nothred";;
+    thread)					echo "test";;
+    nothread)				echo "test/nothred";;
     performance-thread)	    echo ".";;
     performance-nothread)   echo "nothread";;
-    *)			    Die "unknown pathExtension '$1'";;
+    *)						die "unknown pathExtension '$1'";;
   esac
 }
 
@@ -48,7 +40,7 @@ pathExtension() {
 ## =======================================================================
 ##
 
-NHI1_HOME=$(dirname $(dirname $(readlink -f $0)))
+NHI1_HOME=$(dirname $(dirname $(which $0)))
 
 ##  Retrieve environment data
 declare -A lang
@@ -87,7 +79,30 @@ sources ready for compilation.
 EOF
   )"
 
-mkdir -p "$NHI1_TOOL_ROOT" || Die "unable to create directory '$NHI1_TOOL_ROOT'"
+mkdir -p "$NHI1_TOOL_ROOT" || die "unable to create directory '$NHI1_TOOL_ROOT'"
+
+# with '--use-all' det all "--use-*" targets to yes
+if test "$useAll" = "yes" ; then
+  for u in "${!use[@]}" ; do
+	use[$u]="yes"
+  done
+fi
+
+# how many "use" targets are defined?
+declare -i usenum=0
+for u in "${!use[@]}" ; do
+  test "${use[$u]}" = "yes" && let usenum+=1
+done
+
+# minimum one target required
+if (( usenum == 0 )) ; then
+  die "spease specify at lest on of --thread, --nothread, --performance-thread or --performance-nothread"
+fi
+
+# multiple targets need a "--clean" because of reinstalling sme target again
+if (( usenum > 1 )) ; then
+  clean=yes
+fi
 
 for l in ${!lang[@]} ; do
   [[ ${lang[$l]} == 'no' ]] && continue
@@ -103,9 +118,8 @@ for l in ${!lang[@]} ; do
   esac
 
   for t in ${!use[@]} ; do
-    [[ $useAll == 'no' && ${use[$t]} == 'no' ]] && continue
-
-    prefix="$NHI1_TOOL_ROOT/$(pathExtension $t)"
+    [[ ${use[$t]} == 'no' ]] && continue
+    prefix="$NHI1_TOOL_ROOT/$(pathExtension $t)" || die "invalid pathExtension '$t'"
 
     case "$l" in
       perl)
@@ -154,7 +168,7 @@ for l in ${!lang[@]} ; do
 		buildConf+=(--prefix="$prefix")
       ;;
       *)
-		Die "invalid language $1"
+		die "invalid language $1"
       ;;
     esac
 
@@ -162,14 +176,14 @@ for l in ${!lang[@]} ; do
       cd "$l-latest/$buildDir"
       if test "$clean" = "yes" ; then
 		test -f Makefile && {
-		  make distclean || Die "unable to 'make distclean'"
+		  make distclean || die "unable to 'make distclean'"
 		}
       fi
       if test ! -f Makefile ; then
-		bash -norc "$buildScript" "${buildConf[@]}" "$@" || Die "unable to configure"
+		bash -norc "$buildScript" "${buildConf[@]}" "$@" || die "unable to configure"
       fi
-      make -j $Jobs || Die "unable to build"
-      make install || Die "unable to install"
+      make -j $Jobs || die "unable to build"
+      make install || die "unable to install"
     )
 
   done
