SysBind cleanup with RETRY

diff --git a/trunk/bin/Nhi1Docs b/trunk/bin/Nhi1Docs
--- a/trunk/bin/Nhi1Docs
+++ b/trunk/bin/Nhi1Docs
@@ -88,6 +88,11 @@ Directories ... use on of the following targets:
 EOF
 }
 
+Error() {
+  echo "error: $1" 1>&2
+  exit ${2:-1}
+}
+
 eval "$($abs_top_srcdir/sbin/SetupEnv "$0" "$@" <<-'EOF'
 G_Shell 'bash'
 # ---------------------------------------------------------------------
@@ -110,14 +115,8 @@ EOF
     Usage
     exit 1
 }
-[[ "$usedot" == "yes" && -z "$DOT" ]] && {
-    echo "error: dot tool not available, please install" 1>&2
-    exit 1
-}
-[[ -z "$DOXYGEN" ]] && {
-    echo ERROR: no 'doxygen' support available 2>&1
-    exit 1
-}
+[[ "$usedot" == "yes" && -z "$DOT" ]] && Error "dot tool not available, please install"
+[[ -z "$DOXYGEN" ]] && Error "no 'doxygen' support available"
 
 [[ $1 == "ALL" ]] && {
     set -- $abs_srcdir/man $abs_srcdir/*_private $abs_srcdir/main
@@ -130,7 +129,7 @@ EOF
   export  BUILDDIR="$abs_top_builddir/theLink"
   export  VERSION="$LIBMSGQUE_VERSION"
   export  PERL_PATH="$DOXYPERL"
-  export  DOT_PATH="$(dirname $DOT)"
+  export  DOT_PATH="${DOT%/*}"
   export  GENERATE_MAN='NO' 
   export  GENERATE_RTF='NO' 
   export  GENERATE_XML='NO' 
@@ -151,19 +150,10 @@ EOF
   for D
   do
     echo "======================================================================="
-    case "$D" in
-      *_private)
-      ;;
-      *)
-	D+=_private
-      ;;
-    esac
     if test ! -e "$D" ; then
-      D="$abs_srcdir/$D"
-    fi
-    if test ! -e "$D" ; then
-      echo "Error: unable to open directory '$D'"
-      exit 1
+      [[ "$D" != *_private ]] && D+=_private
+      [[ ! -e "$D" ]] && D="$abs_srcdir/${D#$abs_builddir/}"
+      [[ ! -e "$D" ]] && Error "unable to open directory '$D'"
     fi
     if test -f "$D" ; then
       FN="$D"
@@ -171,13 +161,9 @@ EOF
     elif test -d "$D"; then
       FN="$D/Doxyfile*"
     else
-      echo "Error: '$D' ist not a file and not a directory"
-      exit 1
+      Error "'$D' ist not a file and not a directory"
     fi
-    pushd "$D" || {
-      echo "ERROR: $1 is no directory"
-      exit 2
-    }
+    pushd "$D" || Error "$1 is no directory" 2
     shift
     D=$(basename "$D")
 
diff --git a/trunk/bin/Nhi1Test b/trunk/bin/Nhi1Test
--- a/trunk/bin/Nhi1Test
+++ b/trunk/bin/Nhi1Test
@@ -113,57 +113,61 @@ lookup() {
   fi
   declare -a ret
   declare CMDDIR=$(cd $(dirname -- $1);pwd)
-  declare CMD=$(basename -- $1)
+  declare CM1=$(basename -- $1)
+  declare CM2=${CM1%.*}
+  declare lng=${CM1##*.}
 
   # fix the CMD path
-  [[ ! -e "$CMDDIR/$CMD" ]] && {
+  if [[ ! -e "$CMDDIR/$CM1" && ! -e  "$CMDDIR/$CM2" ]] ; then
     # look for CMD in the same directory but in the source tree
     CMDDIR="$abs_top_srcdir/${CMDDIR#$abs_top_builddir/}"
-    [[ ! -e  "$CMDDIR/$CMD" ]] && {
+    if [[ ! -e  "$CMDDIR/$CM1" && ! -e  "$CMDDIR/$CM2" ]] ; then
       # look into the example directories
-      case "$CMD" in
-	*.tcl)      CMDDIR="$abs_top_srcdir/theLink/example/tcl";;
-	*.test)     CMDDIR="$abs_top_srcdir/theLink/tests";;
-	*.java)     CMDDIR="$abs_top_builddir/theLink/example/java";;
-	*.py)	    CMDDIR="$abs_top_srcdir/theLink/example/python";;
-	*.pl)	    CMDDIR="$abs_top_srcdir/theLink/example/perl";;
-	*.rb)	    CMDDIR="$abs_top_srcdir/theLink/example/ruby";;
-	*.php)      CMDDIR="$abs_top_srcdir/theLink/example/php";;
-	*.cs|*.exe) CMDDIR="$abs_top_builddir/theLink/example/csharp";;
-	*.vb)	    CMDDIR="$abs_top_builddir/theLink/example/vb";;
-	*.go)	    CMDDIR="$abs_top_builddir/theLink/example/go";;
-	*.cc)	    CMDDIR="$abs_top_builddir/theLink/example/cc";;
-	*.c)	    CMDDIR="$abs_top_builddir/theLink/example/c";;
+      case "$lng" in
+	tcl)      CMDDIR="$abs_top_srcdir/theLink/example/tcl";;
+	test)     CMDDIR="$abs_top_srcdir/theLink/tests";;
+	java)     CMDDIR="$abs_top_builddir/theLink/example/java";;
+	py)	  CMDDIR="$abs_top_srcdir/theLink/example/python";;
+	pl)	  CMDDIR="$abs_top_srcdir/theLink/example/perl";;
+	rb)	  CMDDIR="$abs_top_srcdir/theLink/example/ruby";;
+	php)      CMDDIR="$abs_top_srcdir/theLink/example/php";;
+	cs|exe)	  CMDDIR="$abs_top_builddir/theLink/example/csharp";;
+	vb)	  CMDDIR="$abs_top_builddir/theLink/example/vb";;
+	go)	  CMDDIR="$abs_top_builddir/theLink/example/go";;
+	cc)	  CMDDIR="$abs_top_builddir/theLink/example/cc";;
+	c)	  CMDDIR="$abs_top_builddir/theLink/example/c";;
       esac
-    }
-  }
+    fi
+  fi
 
-  if [[ -r "$CMDDIR/$CMD" ]] ; then
-    CMD="$CMDDIR/$CMD"
+  if [[ -r "$CMDDIR/$CM1" ]] ; then
+    CM1="$CMDDIR/$CM1"
+  elif [[ -r "$CMDDIR/$CM2" ]] ; then
+    CM1="$CMDDIR/$CM2"
   elif (( ! silent )) ; then
-    Die "unable to find comand-file '$CMD'"
+    Die "unable to find comand-file '$CM1'"
   fi
 
   if (( silent )) ; then
-    echo $CMD
+    echo $CM1
   else 
     # find executable if CMD is a script-file
-    case "$CMD" in
-      *.tcl|*.test)   EXE="${TCLSH:-tclsh}";;
-      *.java)	    EXE="${JAVA:-java}"; CMD="${CMD%.*}";;
-      *.py)	    EXE="${PYTHON:-python}";;
-      *.pl)	    EXE="${PERL:-perl} -I$abs_top_srcdir/theLink/example/perl";;
-      *.rb)	    EXE="${RUBY:-ruby}";;
-      *.php)	    EXE="${PHP:-php}";;
-      *.cs|*.exe)	    EXE="${MONO:-mono}"; CMD="${CMD%.*}.exe";;
-      *.go)	    EXE=""; CMD="${CMD%.*}$EXT";;
-      *.cc)	    EXE=""; CMD="${CMD%.*}$EXT";;
-      *.c)	    EXE=""; CMD="${CMD%.*}$EXT";;
-      *)		    EXE="";;
+    case "$lng" in
+      tcl|test) EXE="${TCLSH:-tclsh}";;
+      java)	EXE="${JAVA:-java}"; CMD="${CMD%.*}";;
+      py)	EXE="${PYTHON:-python}";;
+      pl)	EXE="${PERL:-perl} -I$abs_top_srcdir/theLink/example/perl";;
+      rb)	EXE="${RUBY:-ruby}";;
+      php)	EXE="${PHP:-php}";;
+      cs|exe)   EXE="${MONO:-mono}"; CMD="${CMD%.*}.exe";;
+      go)	EXE=""; CM1="${CM1%.*}$EXT";;
+      cc)	EXE=""; CM1="${CM1%.*}$EXT";;
+      c)	EXE=""; CM1="${CM1%.*}$EXT";;
+      *)	EXE="";;
     esac
 
     test -n "$EXE" && ret+=("$EXE")
-    ret+=("$CMD")
+    ret+=("$CM1")
     echo "${ret[@]}"
   fi
 }
@@ -185,8 +189,6 @@ fi
 export TS_DEBUG=0
 
 PREFIX=""
-POSTFIX="cat"
-TEE="yes"
 
 PREFIX_vg="valgrind --trace-children=yes --num-callers=36 --quiet"
 PREFIX_gdb="gdb -d ../perlmsgque/Net*/ --tui --args"
@@ -206,6 +208,14 @@ case "${1:-}" in
     unset d
   ;;
 esac
+
+if [[ "$1" == *.test || "$1" == *all.tcl ]] ; then
+  TEE="yes"
+  POSTFIX="cat"
+else
+  TEE="no"
+  POSTFIX=""
+fi
 
 ##
 ## =========================================================================
@@ -297,24 +307,27 @@ declare id=all
 
 while (( $# )) ; do
   if [[ "$1" == -* && $first -eq 1 ]] ; then
-    args+=($1)
+    args+=("$1")
   else
     if (( first )) ; then
-      id=$(basename -- ${PWD%/*})_$(basename -- ${1%.*})
-      cmdline+=( $(lookup $1) ${args[@]:-} ) || exit
-      first=0
+      id=$(basename -- "${PWD%/*}")_$(basename -- "${1%.*}")
+      cmdline+=( $(lookup $1) ) || exit
+      (( ${#args[@]} )) && cmdline+=( "${args[@]:-}" )
+      args=()
+      (( first=0 ))
     else
-      cmdline+=( $1 )
+      cmdline+=( "$1" )
       [[ "$1" == "@" ]] && first=1
     fi
   fi
   shift
 done
 
-echo "exec: ${cmdline[*]}"
+IFS=",";echo "exec: [${#cmdline[@]}] ${cmdline[*]}";unset IFS
 
 set "${cmdline[@]}"
-EXE=$1; shift
+
+EXE="$1"; shift
 
 if [[ $TEE == "yes" ]] ; then
   if [[ $PREFIX == *kdbg* ]] ; then
