neu

diff --git a/trunk/bin/rcBuild b/trunk/bin/rcBuild
--- a/trunk/bin/rcBuild
+++ b/trunk/bin/rcBuild
@@ -1,110 +1,5 @@
-#!/bin/bash
-ROOT=$(cd ${0%/*}/..;pwd)
-SKRIPT=$(cd ${0%/*};pwd)/${0##*/}
-BAK=$ROOT/.build
-BUI=/build/$USER
-BUILNK=$ROOT/build
-SF=$BUI/.syncFlag
+#! /bin/bash
 
-ToBak() {
-    test -f $DF && $RSYNC -a "$@" $BUI/ $BAK/
-}
-
-ToBui() {
-    $RSYNC -a "$@" $BAK/ $BUI/
-    touch $SF
-}
-
-CheckRoot() {
-  (( $UID != 0 )) && {
-    echo "ERROR: run this command as root"
-    exit 1
-  }
-}
-
-RSYNC='rsync'
-CMD="$1"; shift
-
-#set -x
-
-case "$CMD" in
-  start)
-    echo starting... $0
-    mkdir -p $BUI
-    rm -fr $BUILNK
-    ln -fs $BUI $BUILNK
-    ToBui
-  ;;
-  stop)
-    echo stopping... $0
-    ToBak --delete
-  ;;
-  2bui)
-    ToBui
-  ;;
-  2bak)
-    ToBak "$@"
-  ;;
-  install)
-    CheckRoot
-    $0 remove
-    ln -s $SKRIPT $START
-    ln -s $SKRIPT $STOP
-    $0 status
-  ;;
-  uninstall)
-    T=/etc/rc.d/rc3.d/K01rcBuild
-    CheckRoot
-    test -L $START && rm $START
-    test -L $STOP  && rm $STOP
-    $0 status
-  ;;
-  status)
-    df $BUI
-  ;;
-  *)
-    echo usage: $0 '(start|stop|2bui|2bak|install|uninstall|status)'
-    exit 4
-  ;;
-esac
-
-exit 0
-
-
-:
-#!/bin/bash
-#
-#     Template LSB system startup script for example service/daemon rcBuild
-#     Copyright (C) 1995--2005  Kurt Garloff, SUSE / Novell Inc.
-#          
-#     This library is free software; you can redistribute it and/or modify it
-#     under the terms of the GNU Lesser General Public License as published by
-#     the Free Software Foundation; either version 2.1 of the License, or (at
-#     your option) any later version.
-#			      
-#     This library is distributed in the hope that it will be useful, but
-#     WITHOUT ANY WARRANTY; without even the implied warranty of
-#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
-#     Lesser General Public License for more details.
-#      
-#     You should have received a copy of the GNU Lesser General Public
-#     License along with this library; if not, write to the Free Software
-#     Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
-#
-# /etc/init.d/rcBuild
-# LSB compatible service control script; see http://www.linuxbase.org/spec/
-# Please send feedback to http://www.suse.de/feedback/
-# 
-# Note: This template uses functions rc_XXX defined in /etc/rc.status on
-# UnitedLinux/SUSE/Novell based Linux distributions. However, it will work
-# on other distributions as well, by using the LSB (Linux Standard Base) 
-# or RH functions or by open coding the needed functions.
-# Read http://www.tldp.org/HOWTO/HighQuality-Apps-HOWTO/ if you prefer not 
-# to use this template.
-#
-# chkconfig: 345 99 00
-# description: rcBuild setup and fill tempfs-build-environment
-# 
 ### BEGIN INIT INFO
 # Provides:          rcBuild
 # Required-Start:    $ALL
@@ -114,103 +9,10 @@ exit 0
 # Default-Start:     3 5
 # Default-Stop:      0 1 2 6
 # Short-Description: rcBuild setup and fill tempfs-build-environment
-# Description:       Start rcBuild to allow to build in the chroot
+# Description:       Start rcBuild to allow to build in an in-memory
 #	environment. First the tempfs is created and than
 #	the tempfs is filled using rsync with the root and the user data.
 ### END INIT INFO
-# 
-# Any extensions to the keywords given above should be preceeded by 
-# X-VendorTag- according to LSB.
-# 
-# Notes on Required-Start/Should-Start:
-# * There are two different issues that are solved by Required-Start
-#    and Should-Start
-# (a) Hard dependencies: This is used by the runlevel editor to determine
-#     which services absolutely need to be started to make the start of
-#     this service make sense. Example: nfsserver should have
-#     Required-Start: $portmap
-#     Also, required services are started before the dependent ones.
-#     The runlevel editor will warn about such missing hard dependencies
-#     and suggest enabling. During system startup, you may expect an error,
-#     if the dependency is not fulfilled.
-# (b) Specifying the init script ordering, not real (hard) dependencies.
-#     This is needed by insserv to determine which service should be
-#     started first (and at a later stage what services can be started
-#     in parallel). The tag Should-Start: is used for this.
-#     It tells, that if a service is available, it should be started
-#     before. If not, never mind.
-# * When specifying hard dependencies or ordering requirements, you can 
-#   use names of services (contents of their Provides: section)
-#   or pseudo names starting with a $. The following ones are available
-#   according to LSB (1.1):
-#	$local_fs		all local file systems are mounted
-#				(most services should need this!)
-#	$remote_fs		all remote file systems are mounted
-#				(note that /usr may be remote, so
-#				 many services should Require this!)
-#	$syslog			system logging facility up
-#	$network		low level networking (eth card, ...)
-#	$named			hostname resolution available
-#	$netdaemons		all network daemons are running
-#   The $netdaemons pseudo service has been removed in LSB 1.2.
-#   For now, we still offer it for backward compatibility.
-#   These are new (LSB 1.2):
-#	$time			the system time has been set correctly	
-#	$portmap		SunRPC portmapping service available
-#   UnitedLinux/SUSE/Novell extensions:
-#	$ALL			indicates that a script should be inserted
-#				at the end
-# * The services specified in the stop tags 
-#   (Required-Stop/Should-Stop)
-#   specify which services need to be still running when this service
-#   is shut down. Often the entries there are just copies or a subset 
-#   from the respective start tag.
-# * Should-Start/Stop are now part of LSB as of 2.0,
-#   formerly SUSE/Unitedlinux used X-UnitedLinux-Should-Start/-Stop.
-#   insserv does support both variants.
-# * X-UnitedLinux-Default-Enabled: yes/no is used at installation time
-#   (%fillup_and_insserv macro in %post of many RPMs) to specify whether
-#   a startup script should default to be enabled after installation.
-#
-# Note on runlevels:
-# 0 - halt/poweroff 			6 - reboot
-# 1 - single user			2 - multiuser without network exported
-# 3 - multiuser w/ network (text mode)  5 - multiuser w/ network and X11 (xdm)
-# 
-# Note on script names:
-# http://www.linuxbase.org/spec/refspecs/LSB_1.3.0/gLSB/gLSB/scrptnames.html
-# A registry has been set up to manage the init script namespace.
-# http://www.lanana.org/
-# Please use the names already registered or register one or use a
-# vendor prefix.
-
-
-# Check for missing binaries (stale symlinks should not happen)
-# Note: Special treatment of stop for LSB conformance
-rcBuild_BIN=/usr/sbin/rcBuild
-test -x $rcBuild_BIN || { echo "$rcBuild_BIN not installed"; 
-	if [ "$1" = "stop" ]; then exit 0;
-	else exit 5; fi; }
-
-# Check for existence of needed config file and read it
-rcBuild_CONFIG=/etc/sysconfig/rcBuild
-test -r $rcBuild_CONFIG || { echo "$rcBuild_CONFIG not existing";
-	if [ "$1" = "stop" ]; then exit 0;
-	else exit 6; fi; }
-
-# Read config	
-. $rcBuild_CONFIG
-
-# Some variables
-rcBuild_PIDFILE=/var/run/rcBuild.pid
-
-# Source LSB init functions
-# providing start_daemon, killproc, pidofproc, 
-# log_success_msg, log_failure_msg and log_warning_msg.
-# This is currently not used by UnitedLinux based distributions and
-# not needed for init scripts for UnitedLinux only. If it is used,
-# the functions from rc.status should not be sourced or used.
-#. /lib/lsb/init-functions
 
 # Shell functions sourced from /etc/rc.status:
 #      rc_check         check and set local and overall rc status
@@ -224,95 +26,28 @@ rcBuild_PIDFILE=/var/run/rcBuild.pid
 #      rc_reset         clear both the local and overall rc status
 #      rc_exit          exit appropriate to overall rc status
 #      rc_active        checks whether a service is activated by symlinks
-
-# Use the SUSE rc_ init script functions;
-# emulate them on LSB, RH and other systems
-
-# Default: Assume sysvinit binaries exist
-start_daemon() { /sbin/start_daemon ${1+"$@"}; }
-killproc()     { /sbin/killproc     ${1+"$@"}; }
-pidofproc()    { /sbin/pidofproc    ${1+"$@"}; }
-checkproc()    { /sbin/checkproc    ${1+"$@"}; }
-if test -e /etc/rc.status; then
-    # SUSE rc script library
-    . /etc/rc.status
-else
-    export LC_ALL=POSIX
-    _cmd=$1
-    declare -a _SMSG
-    if test "${_cmd}" = "status"; then
-	_SMSG=(running dead dead unused unknown reserved)
-	_RC_UNUSED=3
-    else
-	_SMSG=(done failed failed missed failed skipped unused failed failed reserved)
-	_RC_UNUSED=6
-    fi
-    if test -e /lib/lsb/init-functions; then
-	# LSB    
-    	. /lib/lsb/init-functions
-	echo_rc()
-	{
-	    if test ${_RC_RV} = 0; then
-		log_success_msg "  [${_SMSG[${_RC_RV}]}] "
-	    else
-		log_failure_msg "  [${_SMSG[${_RC_RV}]}] "
-	    fi
-	}
-	# TODO: Add checking for lockfiles
-	checkproc() { pidofproc ${1+"$@"} >/dev/null 2>&1; return $?; }
-    elif test -e /etc/init.d/functions; then
-	# RHAT
-	. /etc/init.d/functions
-	echo_rc()
-	{
-	    #echo -n "  [${_SMSG[${_RC_RV}]}] "
-	    if test ${_RC_RV} = 0; then
-		success "  [${_SMSG[${_RC_RV}]}] "
-	    else
-		failure "  [${_SMSG[${_RC_RV}]}] "
-	    fi
-	}
-	checkproc() { status ${1+"$@"}; return $?; }
-	start_daemon() { daemon ${1+"$@"}; return $?; }
-    else
-	# emulate it
-	echo_rc() { echo "  [${_SMSG[${_RC_RV}]}] "; }
-    fi
-    rc_reset() { _RC_RV=0; }
-    rc_failed()
-    {
-	if test -z "$1"; then 
-	    _RC_RV=1;
-	elif test "$1" != "0"; then 
-	    _RC_RV=$1; 
-    	fi
-	return ${_RC_RV}
-    }
-    rc_check()
-    {
-	return rc_failed $?
-    }	
-    rc_status()
-    {
-	rc_failed $?
-	if test "$1" = "-r"; then _RC_RV=0; shift; fi
-	if test "$1" = "-s"; then rc_failed 5; echo_rc; rc_failed 3; shift; fi
-	if test "$1" = "-u"; then rc_failed ${_RC_UNUSED}; echo_rc; rc_failed 3; shift; fi
-	if test "$1" = "-v"; then echo_rc; shift; fi
-	if test "$1" = "-r"; then _RC_RV=0; shift; fi
-	return ${_RC_RV}
-    }
-    rc_exit() { exit ${_RC_RV}; }
-    rc_active() 
-    {
-	if test -z "$RUNLEVEL"; then read RUNLEVEL REST < <(/sbin/runlevel); fi
-	if test -e /etc/init.d/S[0-9][0-9]${1}; then return 0; fi
-	return 1
-    }
-fi
+. /etc/rc.status
 
 # Reset status of this service
 rc_reset
+
+# exit on undef variable
+set -u
+
+# configuration data
+rcBuild_size=1g
+rcBuild_directory=/build
+rcBuild_backup=/backup
+
+#usage: rsync args
+ToBak() {
+  rsync -a "$@" $rcBuild_directory/ $rcBuild_backup/
+}
+
+#usage: rsync args
+ToBui() {
+  rsync -a "$@" $rcBuild_backup/ $rcBuild_directory/
+}
 
 # Return values acc. to LSB for all commands but status:
 # 0	  - success
@@ -330,61 +65,54 @@ rc_reset
 # with force-reload (in case signaling is not supported) are
 # considered a success.
 
+(( $UID != 0 )) && {
+  echo "ERROR: run this command as root"
+  exit 1
+}
+
 case "$1" in
     start)
-	echo -n "Starting rcBuild "
-	## Start daemon with startproc(8). If this fails
-	## the return value is set appropriately by startproc.
-	#start_daemon $rcBuild_BIN
+	echo -n "Starting rcBuild..."
 
-	# setup os-special-dirs
-	mount -o bind /proc	$rcBuild_chroot/proc
-	mount -o bind /dev	$rcBuild_chroot/dev
-	mount -o bind /dev/pts	$rcBuild_chroot/dev/pts
+	# mount build directory
+	if mountpoint -q $rcBuild_directory ; then
+	  echo -n "already mounted..."
+	else
+	  echo -n "mount..."
+	  mount -t tmpfs -o size=$rcBuild_size tmpfs $rcBuild_directory
+	fi
 
-	# setup build directory
-	mount -t tmpfs -o size=$rcBuild_size tmpfs $rcBuild_directory/trunk
+	# fill with backup data
+	(( ! $? )) && {
+	  echo -n "fill..."
+	  ToBui
+	}
 
 	## Remember status and be verbose
 	rc_status -v
-
-	## Update PIDFILE if not automatically written
-	# pidofproc $rcBuild_BIN > $rcBuild_PIDFILE
 	;;
     stop)
 	echo -n "Shutting down rcBuild "
-	## Stop daemon with killproc(8) and if this fails
-	## killproc sets the return value according to LSB.
-	## Usage on RH: killproc [-p pidfile] [-d delay] {progrm} [-signal]
-	
-	## This one signal TERM followed by e.g. signal KILL
-	killproc $rcBuild_BIN
-	## or only with signal TERM
-	# killproc $rcBuild_BIN -TERM	
+
+	# mount build directory
+	if mountpoint -q $rcBuild_directory ; then
+	  # safe the data
+	  echo -n "backup..."
+	  ToBak --delete
+	  (( ! $? )) && {
+	    echo -n "umount..."
+	    umount $rcBuild_directory
+	  }
+	else
+	  echo -n "not mounted..."
+	fi
 
 	## Remember status and be verbose
 	rc_status -v
-
-	## Remove PIDFILE it not automatically renmoved
-	# if test -e $rcBuild_PIDFILE ; then
-	#     rm -f $rcBuild_PIDFILE
-	# fi
 	;;
     try-restart|condrestart)
-	## Do a restart only if the service was active before.
-	## Note: try-restart is now part of LSB (as of 1.9).
-	## RH has a similar command named condrestart.
-	if test "$1" = "condrestart"; then
-		echo "${attn} Use try-restart ${done}(LSB)${attn} rather than condrestart ${warn}(RH)${norm}"
-	fi
-	$0 status
-	if test $? = 0; then
-		$0 restart
-	else
-		rc_reset	# Not running is not a failure.
-	fi
-	## Remember status and be quiet
-	rc_status
+	## unused
+	rc_status -u
 	;;
     restart)
 	## Stop the service and regardless of whether it was
@@ -396,39 +124,31 @@ case "$1" in
 	rc_status
 	;;
     force-reload)
-	## Signal the daemon to reload its config. Most daemons
-	## do this on signal 1 (SIGHUP).
-	## If it does not support it, restart the service if it
-	## is running.
+	echo -n "Reload service rcBuild..."
 
-	echo -n "Reload service rcBuild "
-	## if it supports it:
-	killproc -HUP $rcBuild_BIN
-	#touch /var/run/rcBuild.pid
+	# send data to build directory, delete new data
+	ToBui --delete
+
 	rc_status -v
-
-	## Otherwise:
-	#$0 try-restart
-	#rc_status
 	;;
     reload)
-	## Like force-reload, but if daemon does not support
-	## signaling, do nothing (!)
+	echo -n "Reload service rcBuild..."
 
-	## If it supports signaling:
-	echo -n "Reload service rcBuild "
-	killproc -HUP $rcBuild_BIN
-	#touch /var/run/rcBuild.pid
+	# send data to build directory, do NOT delete new data
+	ToBui --update
+
 	rc_status -v
-	
-	## Otherwise if it does not support reload:
-	#rc_failed 3
-	#rc_status -v
+	;;
+    backup)
+	echo -n "Backup service rcBuild..."
+
+	# send data to backup directory
+	ToBak --delete
+
+	rc_status -v
 	;;
     status)
 	echo -n "Checking for service rcBuild "
-	## Check status with checkproc(8), if process is running
-	## checkproc will return with exit status 0.
 
 	## Return value is slightly different for the status command:
 	## 0 - service up and running
@@ -438,8 +158,11 @@ case "$1" in
 	## 4 - service status unknown :-(
 	## 5--199 reserved (5--99 LSB, 100--149 distro, 150--199 appl.)
 	
-	## NOTE: checkproc returns LSB compliant status values.
-	checkproc $rcBuild_BIN
+	if mountpoint -q $rcBuild_directory ; then
+	  rc_failed 0
+	else
+	  rc_failed 3
+	fi
 	## NOTE: rc_status knows that we called this init script with
 	## "status" option and adapts its messages accordingly.
 	rc_status -v
@@ -448,11 +171,31 @@ case "$1" in
 	## Optional: Probe for the necessity of a reload, print out the
 	## argument to this init script which is required for a reload.
 	## Note: probe is not (yet) part of LSB (as of 1.9)
-
-	test /etc/rcBuild/rcBuild.conf -nt /var/run/rcBuild.pid && echo reload
+	rc_status -u
+	;;
+    install)
+	echo -n "install rcBuild..."
+	if [[ -f "/etc/init.d/rcBuild" ]] ; then
+	  echo -n "allready done..."
+	else
+	  rm -f /etc/init.d/rcBuild && \
+	    cp $0 /etc/init.d/rcBuild && \
+	      /sbin/insserv /etc/init.d/rcBuild
+	fi
+	rc_status -v
+	;;
+    uninstall)
+	echo -n "uninstall rcBuild..."
+	if [[ ! -f "/etc/init.d/rcBuild" ]] ; then
+	  echo -n "allready done..."
+	else
+	  /sbin/insserv -r rcBuild && \
+	    rm -f /etc/init.d/rcBuild
+	fi
+	rc_status -v
 	;;
     *)
-	echo "Usage: $0 {start|stop|status|try-restart|restart|force-reload|reload|probe}"
+	echo "Usage: $0 {start|stop|status|restart|force-reload|reload|backup|install|uninstall}"
 	exit 1
 	;;
 esac
