neu

diff --git a/trunk/bin/SetupEnv b/trunk/bin/SetupEnv
--- a/trunk/bin/SetupEnv
+++ b/trunk/bin/SetupEnv
@@ -51,7 +51,7 @@ Functions:
       > print configuration after setup
     call-in-loop
       > loop over the SetupEnv to run external tests
-  G_Arguments <string>
+  G_Argument <string>
     The String has the form :
       > Option:Variable:InitValue:Description?:Type?:ListEntry1?:ListEntry2?:...
     with
@@ -64,6 +64,7 @@ Functions:
 	B) Boolean    -> A boolean variable, default '0' or '1'
 	E) Extern     -> Should the Variable be exported
 	L) List       -> This is a 'List' with values following after
+	A) Array      -> Values will be appended to the variable
       List .......... List entries, only use with Type (B)oolean or (L)ist.
                       As Type (B)oolean only 2 List-Arguments are supported
 
@@ -97,13 +98,13 @@ Eval() 		{
     3)	  echo "eval \"$1\"\;"	;;
   esac
 }
-Error() 	{ Print "$G_FileName ERROR: $1" 	; echo "exit ${2:-1};" ; exit ${2:-1} ; }
-Error2() 	{ Print "$G_FileName ERROR: $1" 	; echo "ERROR $1" ; exit ${2:-1} ; }
-Error3() 	{ Print "$G_FileName ERROR: $1" 	; exit ${2:-1} ; }
-Warning() 	{ Print "$G_FileName WARNING: $1" 	; export SE_SUCCESS ; SE_SUCCESS=1 ; }
-Exit() 		{ Print "$1" 				; echo "exit 0;" ; exit 0 ; }
-Weiter()	{ declare Tmp="";read -p "\n\n   continue with keypress   " Tmp 1>&2 ;}
-Print()		{ echo -e "$*" 1>&2; }
+Error() 	{ Print "$G_FileName ERROR: $1\n" 	; echo "exit ${2:-1};" ; exit ${2:-1} ; }
+Error2() 	{ Print "$G_FileName ERROR: $1\n" 	; echo "ERROR $1" ; exit ${2:-1} ; }
+Error3() 	{ Print "$G_FileName ERROR: $1\n" 	; exit ${2:-1} ; }
+Warning() 	{ Print "$G_FileName WARNING: $1\n" 	; export SE_SUCCESS ; SE_SUCCESS=1 ; }
+Exit() 		{ Print "$1\n" 				; echo "exit 0;" ; exit 0 ; }
+Weiter()	{ declare Tmp="";Print  "\n\n   continue with keypress   "; read Tmp 1>&2 ;}
+Print()		{ printf "$@" 1>&2; }
 
 #XPrint()	{ for __I; do eval echo -en "\"$__I<\$$__I>\", " 1>&2; done; Print "" ; }
 
@@ -382,6 +383,7 @@ function G_Argument {
   def=$3
   dfi=${4:-"No text for <$var>"}
   typ=${5:-}
+  #[[ "$typ" == *A* ]] && var+=":$opt"
   #Print "opt<$opt>, var<$var>, def<$def>, dfi<$dfi>, typ<$typ>"
 ## 1. name of the option
   # POST
@@ -423,14 +425,6 @@ function G_Argument {
   SE_NOptions+=1
 }
 
-function parse_configuration {
-  IFS=$SE_IFS2	
-  for option in "${SE_CmdLine[@]:-}" ; do
-    G_Argument "$option"
-  done
-  IFS=$SE_IFS
-}
-
 function source { 
 ## Soll verhindern das eine Datei 2x eingelesen wird
   [[ -f $1 ]] && {
@@ -461,19 +455,21 @@ function variable_usage {
   (( SE_NOptions == 0 )) && return
   Print "\n  environment database parameter:\n"
   declare -i	 i=0
+  printf "    %13s : %4s : description\n" "variable" "type" 1>&2
+  printf "    %13s : %4s : -----------\n" "--------" "----" 1>&2
   while (( i < SE_NOptions ))
   do
     if [[ -n ${SE_List[$i]} ]] ; then
-      printf "    %13s : %3s : ${SE_Descriptions[$i]} (${SE_List[$i]})\n" "${SE_Variables[$i]}" "${SE_Type[$i]}" 1>&2
+      printf "    %13s : %4s : ${SE_Descriptions[$i]} (${SE_List[$i]})\n" "${SE_Variables[$i]}" "${SE_Type[$i]}" 1>&2
     else
-      printf "    %13s : %3s : ${SE_Descriptions[$i]}\n" "${SE_Variables[$i]}" "${SE_Type[$i]}" 1>&2
+      printf "    %13s : %4s : ${SE_Descriptions[$i]}\n" "${SE_Variables[$i]}" "${SE_Type[$i]}" 1>&2
     fi
     let i+=1
   done
   Print "\n  type definition:\n\n    <B>  boolean variable\n    <E>  export  variable\n    <L>  list    variable" 
 }
 
-function get_variable_usage {
+function get_environment_usage {
   ## work
   Print "\nvariable-usage: $G_FileName"
   command_usage
@@ -486,7 +482,7 @@ function get_detail_user_usage {
     Eval "$G_HelpProc 1>&2"
     Exit ""
   else
-    Error "the user-detail-usage is not installed"
+    Error "the user-detail-usage is not installed, use 'G_HelpProc' to add"
   fi
 }
 
@@ -511,7 +507,7 @@ function get_user_usage {
     else
       space="-${SE_Options[$i]}   ${SE_Descriptions[$i]}"
     fi
-    printf "    %-${max}s =  ${SE_Defaults[$i]:0:30}\n" "$space" 1>&2
+    Print "    %-${max}s =  ${SE_Defaults[$i]:0:30}\n" "$space"
     i+=1
   done
   (( SE_NLOptions > 0 )) && { Print "\n  Custom long options:\n" ; }
@@ -524,22 +520,23 @@ function get_user_usage {
     else
       space3="${SE_Descriptions[$i]}"
     fi
-    printf "    %-${max2}s\n         %-${max3}s =  ${SE_Defaults[$i]:0:30}\n"  "--${SE_Options[$i]}" "$space3" 1>&2
+    Print "    %-${max2}s\n         %-${max3}s =  ${SE_Defaults[$i]:0:30}\n"  "--${SE_Options[$i]}" "$space3"
     i+=1
   done
-  Ret="\n  Global options:\n"
-  Ret+="\n    -c .............. clean screen"
-  Ret+="\n    -v .............. get the version information"
-  Ret+="\n    -i(+) ........... use (not) the interactive mode"
-  Ret+="\n    -s(+) ........... save (not) the configuration"
-  Ret+="\n    -p(+) ........... print (not) the configuration"
-  Ret+="\n    --help,-h ....... get user usage"
-  Ret+="\n    --help-data ..... get variable usage"
-  Ret+="\n    --help-setup .... get setup usage"
-  [[ -n "${G_HelpProc:-}" ]] && \
-    Ret+="\n    --help-detail ... get detail user usage"
-  Ret+="\n\n  File description:\n\n$G_Description\n"
-  Echo "$Ret"
+  Print "\n  Global options:\n"
+  for t in  "-c:clean screen" \
+	    "-v:get the version information" \
+	    "-i(+):use (not) the interactive mode" \
+	    "-s(+):save (not) the configuration" \
+	    "-p(+):print (not) the configuration" \
+	    "--help,-h:get user usage" \
+	    "--help-environment:get environment database usage" \
+	    "--help-setup:get setup usage"
+  do
+    IFS=":"; set -- $t; unset IFS
+    Print "\n    %-18s : %s" "$1" "$2"
+  done
+  Print '\n\n'
 }
 
 function parse_commandline {
@@ -557,14 +554,14 @@ function parse_commandline {
       case $1 in
 	-i) shift; let SE_INTERACTIV=1; continue ;;
 	+i) shift; let SE_INTERACTIV=0; continue ;;
-	-c) shift; Print $clear	; continue ;;
+	-c) shift; Print "$clear"; continue ;;
 	-s) shift; let SE_SAVE=1; continue ;;
 	+s) shift; let SE_SAVE=0; continue ;;
 	-p) shift; let SE_PrintCfg=1; continue ;;
 	+p) shift; let SE_PrintCfg=0; continue ;;
 	-v) shift; Exit "$G_Date - $G_Revision"	; continue ;;
 	-h|--help) shift; let SE_HELP=1; continue ;;
-	--help-data) shift; let SE_HELP=2; continue ;;
+	--help-environment) shift; let SE_HELP=2; continue ;;
 	--help-setup) shift; let SE_HELP=3; continue ;;
 	--help-detail) shift; let SE_HELP=4; continue ;;
       esac
@@ -617,7 +614,7 @@ function parse_commandline {
   ## Help needed
   case $SE_HELP in
     1)	get_user_usage;;
-    2)	get_variable_usage;;
+    2)	get_environment_usage;;
     3)	get_setup_usage;;
     4)	get_detail_user_usage;;
   esac
@@ -628,8 +625,6 @@ function create_mask {
   (( SE_NOptions == 0 )) && return
 ## declare
   declare -i i=0
-  declare R=""
-  declare M=""
 ## make output
   while (( i < SE_NOptions ))
   do
@@ -638,11 +633,9 @@ function create_mask {
     else
       just="${SE_Descriptions[$i]}"
     fi
-    M=$(printf "%-${SE_NDescriptions}s = ${SE_Defaults[$i]:0:30}" "$just")
-    R+="$M$SE_NL"
+    Print "%-${SE_NDescriptions}s = ${SE_Defaults[$i]:0:30}\n" "$just"
     let i+=1
   done
-  echo "$R"
 }
 
 function read_variable {
@@ -650,18 +643,14 @@ function read_variable {
   declare tmp=""
   declare -a tmpl
   if [[ ${SE_Type[$1]} == *B* ]] ; then
-    IFS="|"
-    tmpl=(${SE_List[$1]})
-    unset IFS
+    IFS="|"; tmpl=(${SE_List[$1]}); unset IFS
     if [[ ${SE_Defaults[$1]} == "${tmpl[0]}" ]] ; then 
       tmp=${tmpl[1]}
     else
       tmp=${tmpl[0]}
     fi
   elif [[ ${SE_Type[$1]} == *L* ]] ; then
-    IFS="|"
-    tmpl=(${SE_List[$1]})
-    unset IFS
+    IFS="|"; tmpl=(${SE_List[$1]}); unset IFS
     declare def=${SE_Defaults[$1]}
     if [[ $def == "?" ]] ; then
       tmp=${tmpl[0]}
@@ -684,7 +673,7 @@ function read_variable {
     fi
   else
     IFS=$SE_IFS3
-    Print "$SE_NL<${SE_Defaults[$1]}>\n\nnothing <> for preserving the value\nmarks <\"\"> for clean the value\n"
+    Print "\n<${SE_Defaults[$1]}>\n\nnothing <> for preserving the value\nmarks <\"\"> for clean the value\n"
     read -e -p '==> ' tmp
     IFS=$SE_IFS
     [[ $tmp == "" ]] && return
@@ -696,9 +685,10 @@ function read_variable {
 function print_configuration {
 ## something to do
   (( SE_PrintCfg == 0 || SE_NOptions == 0 )) && return
-## output
-  SE_XXX="==================================================="
-  Echo "$SE_NL  $G_FileName - Configuration$SE_NL$SE_XXX$SE_NL$(create_mask)$SE_NL$SE_XXX$SE_NL"
+  Print "\n  $G_FileName - Configuration\n"
+  Print "===================================================\n"
+  create_mask
+  Print "===================================================\n"
 }
 
 function print_var {
@@ -752,37 +742,39 @@ function interactive {
   REPLY=1
 ## make select
   COLUMNS=1
+  exec 0</dev/tty
+#set -x
   while [[ -n $REPLY ]]
   do
     IFS=$SE_IFS3
-    Print $clear
+    Print "$clear"
     Print "Please check the following items:"
     Print "CTRL-H del char, CTRL-W del word,  CTRL-D for finish\n"
     Print " c) continue\n q) quit\n p) print commands\n"
     while true ; do
       i=0
     ## print screen
-      for m in $(create_mask); do
-	printf "%2i) %s\n" $i "$m" 1>&2
+      for m in $(create_mask 2>&1); do
+	Print "%2i) %s\n" $i "$m"
 	let i+=1
       done
     ## read the commands
-      Print "${SE_NL}Please select a number between [1] and [$SE_NOptions]${SE_NL}"
-      read -e -p "=> "
+      Print "\nPlease select a number between [1] and [$SE_NOptions]\n"
+      read -e -rp "=> "
     ## check the 'read' value
       case $REPLY in
 	[0-9])	    read_variable $REPLY;;
 	[1-9][0-9]) read_variable $REPLY;;
 	c)	    REPLY="";;
-	q)	    Print $clear ; Exit "quitting ..." ;;
-	p)	    print_commands ; Weiter;;
+	q)	    Print "$clear" ; Exit "quitting ..." ;;
+	p)	    command_usage ; Weiter;;
       esac
       break
     done
     IFS=${SE_IFS}
   done
 ## make output
-  Print $clear
+  Print "$clear"
 }
 
 
@@ -903,19 +895,6 @@ Debug "Setup local .ENV file" ##################################################
 #  G_Args+=(-i -s)
 #  SE_LENV="$SE_Setup"
 #}
-
-##
-Debug "Setup Configuration" #######################################################################
-##
-
-#parse_configuration
-
-#print_array SE_Options
-#print_array SE_Variables
-#print_array SE_Defaults
-#print_array SE_Descriptions
-#print_array SE_Type
-#print_array SE_List
 
 ##
 Debug "Environment Variables" ####################################################################
